# -*- coding: utf-8 -*-
"""cnn_proj2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WhmhV_L-J7KJV6HlGh7xSo-0NB1ylS1I
"""

################################################################################
#
# LOGISTICS
#
#    Name: Lakshmeesha Shetty
#    UTD ID : LSS180005
#
# DESCRIPTION
#
#    Image classification in PyTorch for ImageNet reduced to 100 classes and
#    down sampled such that the short side is 64 pixels and the long side is
#    >= 64 pixels
#
#    This script achieved a best accuracy of 69.08% on epoch 40 with a learning
#    rate at that point of 0.001 and time required for each epoch of ~ 205 s
#
# INSTRUCTIONS
#
#    1. Go to Google Colaboratory: https://colab.research.google.com/notebooks/welcome.ipynb
#    2. File - New Python 3 notebook
#    3. Cut and paste this file into the cell (feel free to divide into multiple cells)
#    4. Runtime - Run all
#
# NOTES
#
#    0. For a mapping of category names to directory names see:
#       https://gist.github.com/aaronpolhamus/964a4411c0906315deb9f4a3723aac57
#
#    1. The original 2012 ImageNet images are down sampled such that their short
#       side is 64 pixels (the other side is >= 64 pixels) and only 100 of the
#       original 1000 classes are kept.
#
#    2. Build and train a RegNetX image classifier modified as follows:
#
#       - Set stride = 1 (instead of stride = 2) in the stem
#       - Replace the first stride = 2 down sampling building block in the
#         original network by a stride = 1 normal building block
#       - The fully connected layer in the decoder outputs 100 classes instead
#         of 1000 classes
#
#       The original RegNetX takes in 3x224x224 input images and generates Nx7x7
#       feature maps before the decoder, this modified RegNetX will take in
#       3x56x56 input images and generate Nx7x7 feature maps before the decoder.
#       For reference, an implementation of this network took ~ 112 s per epoch
#       for training, validation and checkpoint saving on Sep 27, 2020 using a
#       free GPU runtime in Google Colab.
#
################################################################################

################################################################################
#
# IMPORT
#
################################################################################

# torch
import torch
import torch.nn       as     nn
import torch.optim    as     optim
from   torch.autograd import Function

# torch utils
import torchvision
import torchvision.transforms as transforms

# additional libraries
import os
import urllib.request
import zipfile
import time
import math
import numpy             as np
import matplotlib.pyplot as plt

################################################################################
#
# PARAMETERS
#
################################################################################

# data
DATA_DIR_1        = 'data'
DATA_DIR_2        = 'data/imagenet64'
DATA_DIR_TRAIN    = 'data/imagenet64/train'
DATA_DIR_TEST     = 'data/imagenet64/val'
DATA_FILE_TRAIN_1 = 'Train1.zip'
DATA_FILE_TRAIN_2 = 'Train2.zip'
DATA_FILE_TRAIN_3 = 'Train3.zip'
DATA_FILE_TRAIN_4 = 'Train4.zip'
DATA_FILE_TRAIN_5 = 'Train5.zip'
DATA_FILE_TEST_1  = 'Val1.zip'
DATA_URL_TRAIN_1  = 'https://github.com/arthurredfern/UT-Dallas-CS-6301-CNNs/raw/master/Data/Train1.zip'
DATA_URL_TRAIN_2  = 'https://github.com/arthurredfern/UT-Dallas-CS-6301-CNNs/raw/master/Data/Train2.zip'
DATA_URL_TRAIN_3  = 'https://github.com/arthurredfern/UT-Dallas-CS-6301-CNNs/raw/master/Data/Train3.zip'
DATA_URL_TRAIN_4  = 'https://github.com/arthurredfern/UT-Dallas-CS-6301-CNNs/raw/master/Data/Train4.zip'
DATA_URL_TRAIN_5  = 'https://github.com/arthurredfern/UT-Dallas-CS-6301-CNNs/raw/master/Data/Train5.zip'
DATA_URL_TEST_1   = 'https://github.com/arthurredfern/UT-Dallas-CS-6301-CNNs/raw/master/Data/Val1.zip'
DATA_BATCH_SIZE   = 512
DATA_NUM_WORKERS  = 4
DATA_NUM_CHANNELS = 3
DATA_NUM_CLASSES  = 100
DATA_RESIZE       = 64
DATA_CROP         = 56
DATA_MEAN         = (0.485, 0.456, 0.406)
DATA_STD_DEV      = (0.229, 0.224, 0.225)

# model
MODEL_STAGE_1_BLOCKS   = 1
MODEL_STAGE_2_BLOCKS   = 1
MODEL_STAGE_3_BLOCKS   = 4
MODEL_STAGE_4_BLOCKS   = 7
MODEL_STAGE_1_CHANNELS = 24
MODEL_STAGE_2_CHANNELS = 56
MODEL_STAGE_3_CHANNELS = 152
MODEL_STAGE_4_CHANNELS = 368
GROUP_WIDTH = 8


# training (linear warm up with cosine decay learning rate)
TRAINING_LR_MAX          = 0.001
TRAINING_LR_INIT_SCALE   = 0.01
TRAINING_LR_INIT_EPOCHS  = 5
TRAINING_LR_FINAL_SCALE  = 0.01
TRAINING_LR_FINAL_EPOCHS = 35
# TRAINING_LR_FINAL_EPOCHS = 2 # uncomment for a quick test
TRAINING_NUM_EPOCHS      = TRAINING_LR_INIT_EPOCHS + TRAINING_LR_FINAL_EPOCHS
TRAINING_LR_INIT         = TRAINING_LR_MAX*TRAINING_LR_INIT_SCALE
TRAINING_LR_FINAL        = TRAINING_LR_MAX*TRAINING_LR_FINAL_SCALE


# file
FILE_NAME = 'RegnetXCnn.pt'
FILE_SAVE = 0
FILE_LOAD = 0

################################################################################
#
# DATA
#
################################################################################

# create a local directory structure for data storage
if (os.path.exists(DATA_DIR_1) == False):
    os.mkdir(DATA_DIR_1)
if (os.path.exists(DATA_DIR_2) == False):
    os.mkdir(DATA_DIR_2)
if (os.path.exists(DATA_DIR_TRAIN) == False):
    os.mkdir(DATA_DIR_TRAIN)
if (os.path.exists(DATA_DIR_TEST) == False):
    os.mkdir(DATA_DIR_TEST)

# download data
if (os.path.exists(DATA_FILE_TRAIN_1) == False):
    urllib.request.urlretrieve(DATA_URL_TRAIN_1, DATA_FILE_TRAIN_1)
if (os.path.exists(DATA_FILE_TRAIN_2) == False):
    urllib.request.urlretrieve(DATA_URL_TRAIN_2, DATA_FILE_TRAIN_2)
if (os.path.exists(DATA_FILE_TRAIN_3) == False):
    urllib.request.urlretrieve(DATA_URL_TRAIN_3, DATA_FILE_TRAIN_3)
if (os.path.exists(DATA_FILE_TRAIN_4) == False):
    urllib.request.urlretrieve(DATA_URL_TRAIN_4, DATA_FILE_TRAIN_4)
if (os.path.exists(DATA_FILE_TRAIN_5) == False):
    urllib.request.urlretrieve(DATA_URL_TRAIN_5, DATA_FILE_TRAIN_5)
if (os.path.exists(DATA_FILE_TEST_1) == False):
    urllib.request.urlretrieve(DATA_URL_TEST_1, DATA_FILE_TEST_1)

# extract data
with zipfile.ZipFile(DATA_FILE_TRAIN_1, 'r') as zip_ref:
    zip_ref.extractall(DATA_DIR_TRAIN)
with zipfile.ZipFile(DATA_FILE_TRAIN_2, 'r') as zip_ref:
    zip_ref.extractall(DATA_DIR_TRAIN)
with zipfile.ZipFile(DATA_FILE_TRAIN_3, 'r') as zip_ref:
    zip_ref.extractall(DATA_DIR_TRAIN)
with zipfile.ZipFile(DATA_FILE_TRAIN_4, 'r') as zip_ref:
    zip_ref.extractall(DATA_DIR_TRAIN)
with zipfile.ZipFile(DATA_FILE_TRAIN_5, 'r') as zip_ref:
    zip_ref.extractall(DATA_DIR_TRAIN)
with zipfile.ZipFile(DATA_FILE_TEST_1, 'r') as zip_ref:
    zip_ref.extractall(DATA_DIR_TEST)

# transforms
transform_train = transforms.Compose([transforms.RandomResizedCrop(DATA_CROP), transforms.RandomHorizontalFlip(p=0.5), transforms.ToTensor(), transforms.Normalize(DATA_MEAN, DATA_STD_DEV)])
transform_test  = transforms.Compose([transforms.Resize(DATA_RESIZE), transforms.CenterCrop(DATA_CROP), transforms.ToTensor(), transforms.Normalize(DATA_MEAN, DATA_STD_DEV)])

# data sets
dataset_train = torchvision.datasets.ImageFolder(DATA_DIR_TRAIN, transform=transform_train)
dataset_test  = torchvision.datasets.ImageFolder(DATA_DIR_TEST,  transform=transform_test)

# data loader
dataloader_train = torch.utils.data.DataLoader(dataset_train, batch_size=DATA_BATCH_SIZE, shuffle=True,  num_workers=DATA_NUM_WORKERS, pin_memory=True, drop_last=True)
dataloader_test  = torch.utils.data.DataLoader(dataset_test,  batch_size=DATA_BATCH_SIZE, shuffle=False, num_workers=DATA_NUM_WORKERS, pin_memory=True, drop_last=True)

################################################################################
#
# NETWORK BUILDING BLOCK
#
################################################################################

# X block
class XBlock(nn.Module):

    # initialization
    def __init__(self, Ni, No, G, Type):

        # parent initialization
        super(XBlock, self).__init__()

        #Adjust Stride for different XBlock
        self.Type = Type
        if Type:
          s = 1
        else:
          s = 2

        #1 X 1/1 
        self.xblock = nn.ModuleList()
        self.xblock.append(nn.Conv2d(Ni, No, (1, 1), stride=(1, 1), padding=(0, 0), dilation=(1, 1), groups=1, bias=False, padding_mode='zeros'))
        self.xblock.append(nn.BatchNorm2d(No, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True))
        self.xblock.append(nn.ReLU())

        #3 X 3/s 
        self.xblock.append(nn.Conv2d(No, No, (3, 3), stride=(s, s), padding=(1, 1), dilation=(1, 1), groups=8, bias=False, padding_mode='zeros'))
        self.xblock.append(nn.BatchNorm2d(No, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True))
        self.xblock.append(nn.ReLU())

        #1 X 1/1
        self.xblock.append(nn.Conv2d(No, No, (1, 1), stride=(1, 1), padding=(0, 0), dilation=(1, 1), groups=1, bias=False, padding_mode='zeros'))
        self.xblock.append(nn.BatchNorm2d(No, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True))
        self.xblock.append(nn.ReLU())

        #1 X 1/2
        self.stride2_block = nn.ModuleList()
        self.stride2_block.append(nn.Conv2d(Ni, No, (1, 1), stride=(2, 2), padding=(0, 0), dilation=(1, 1), groups=1, bias=False, padding_mode='zeros'))
        self.stride2_block.append(nn.BatchNorm2d(No, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True))
        self.stride2_block.append(nn.ReLU())

        



    # forward path
    def forward(self, x):

        y = x
        for layer in self.xblock:
          x = layer(x)
        if self.Type == False:
          for layer in self.stride2_block:
            y = layer(y)
        x = y + x    

        return x

################################################################################
#
# NETWORK
#
################################################################################

# define
class Model(nn.Module):

    # initialization
    def __init__(self,data_num_channels,data_num_classes,model_stage_1_blocks,model_stage_2_blocks,model_stage_3_blocks,model_stage_4_blocks,model_stage_1_channels,model_stage_2_channels,model_stage_3_channels,model_stage_4_channels,group_width):

        # parent initialization
        super(Model, self).__init__()

        #STEM
        self.stem = nn.ModuleList()
        self.stem.append(nn.Conv2d(data_num_channels, model_stage_1_channels, (3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), groups=1, bias=False, padding_mode='zeros'))
        self.stem.append(nn.BatchNorm2d(model_stage_1_channels, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True))
        self.stem.append(nn.ReLU())

        #STAGE1
        self.stage_1 = nn.ModuleList()
        xblock_s1obj = XBlock(model_stage_1_channels,model_stage_1_channels,group_width,True)
        self.stage_1.append(xblock_s1obj)

        #STAGE2
        self.stage_2 = nn.ModuleList()
        xblock_s2obj = XBlock(model_stage_1_channels,model_stage_2_channels,group_width,False)
        self.stage_2.append(xblock_s2obj)


        #STAGE3
        self.stage_3 = nn.ModuleList()
        for i in range(0,model_stage_3_blocks):
          if i==0:
            xblock_s3obj = XBlock(model_stage_2_channels,model_stage_3_channels,group_width,False)
          else:
            xblock_s3obj = XBlock(model_stage_3_channels,model_stage_3_channels,group_width,True)
          self.stage_3.append(xblock_s3obj)


        #STAGE4
        self.stage_4 = nn.ModuleList()
        for i in range(0,model_stage_4_blocks):
          if i==0:
            xblock_s4obj = XBlock(model_stage_3_channels,model_stage_4_channels,group_width,False)
          else:
            xblock_s4obj = XBlock(model_stage_4_channels,model_stage_4_channels,group_width,True)
          self.stage_4.append(xblock_s4obj)


        #HEAD
        self.head = nn.ModuleList()
        self.head.append(nn.AdaptiveAvgPool2d((1, 1)))
        self.head.append(nn.Flatten())
        self.head.append(nn.Linear(model_stage_4_channels, data_num_classes, bias=True))


        

      
      

    # forward path
    def forward(self, x):

        #STEM
        for layer in self.stem:
          x = layer(x)

        #STAGE 1
        for layer in self.stage_1:
          x = layer(x)
        

        #STAGE 2
        for layer in self.stage_2:
          x = layer(x)

        #STAGE 3
        for layer in self.stage_3:
          x = layer(x)

        #STAGE 4
        for layer in self.stage_4:
          x = layer(x)

        #HEAD
        for layer in self.head:
          x = layer(x)


        return x

# create
model = Model(DATA_NUM_CHANNELS,DATA_NUM_CLASSES,MODEL_STAGE_1_BLOCKS,MODEL_STAGE_2_BLOCKS,MODEL_STAGE_3_BLOCKS,MODEL_STAGE_4_BLOCKS,MODEL_STAGE_1_CHANNELS,MODEL_STAGE_2_CHANNELS,MODEL_STAGE_3_CHANNELS,MODEL_STAGE_4_CHANNELS,GROUP_WIDTH)

start_epoch = 0

# learning rate schedule
def lr_schedule(epoch):

    # linear warmup followed by cosine decay
    if epoch < TRAINING_LR_INIT_EPOCHS:
        lr = (TRAINING_LR_MAX - TRAINING_LR_INIT)*(float(epoch)/TRAINING_LR_INIT_EPOCHS) + TRAINING_LR_INIT
    else:
        lr = (TRAINING_LR_MAX - TRAINING_LR_FINAL)*max(0.0, math.cos(((float(epoch) - TRAINING_LR_INIT_EPOCHS)/(TRAINING_LR_FINAL_EPOCHS - 1.0))*(math.pi/2.0))) + TRAINING_LR_FINAL

    return lr





# enable data parallelization for multi GPU systems
if (torch.cuda.device_count() > 1):
    model = nn.DataParallel(model)
print('Using {0:d} GPU(s)'.format(torch.cuda.device_count()), flush=True)

################################################################################
#
# ERROR AND OPTIMIZER
#
################################################################################


# error (softmax cross entropy)
criterion = nn.CrossEntropyLoss()

# optimizer
optimizer = optim.Adam(model.parameters(), lr=0.001, betas=(0.9, 0.999), eps=1e-08, weight_decay=0, amsgrad=False)


# specify the device as the GPU if present with fallback to the CPU
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")


# transfer the network to the device
model.to(device)


# model loading
if FILE_LOAD == 1:
    checkpoint = torch.load(FILE_NAME)
    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    start_epoch = checkpoint['epoch'] + 1


################################################################################
#
# TRAINING
#
################################################################################




# cycle through the epochs
for epoch in range(start_epoch, TRAINING_NUM_EPOCHS):

    # initialize train set statistics
    model.train()
    training_loss = 0.0
    num_batches   = 0

    # set the learning rate for the epoch
    for g in optimizer.param_groups:
        g['lr'] = lr_schedule(epoch)
    

    print("Start of epoch:"+str(epoch+1))
    start_time = time.time()

    # cycle through the train set
    for data in dataloader_train:

        # extract a batch of data and move it to the appropriate device
        inputs, labels = data
        inputs, labels = inputs.to(device), labels.to(device)

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward pass, loss, backward pass and weight update
        outputs = model(inputs)
        loss    = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # update statistics
        training_loss = training_loss + loss.item()
        num_batches   = num_batches + 1



    # initialize test set statistics
    model.eval()
    test_correct = 0
    test_total   = 0

    # no weight update / no gradient needed
    with torch.no_grad():

        # cycle through the test set
        for data in dataloader_test:

            # extract a batch of data and move it to the appropriate device
            inputs, labels = data
            inputs, labels = inputs.to(device), labels.to(device)

            # forward pass and prediction
            outputs      = model(inputs)
            _, predicted = torch.max(outputs.data, 1)

            # update test set statistics
            test_total   = test_total + labels.size(0)
            test_correct = test_correct + (predicted == labels).sum().item()

    # epoch statistics
    print("Time taken to complete epoch"+str(epoch+1))
    print("--- %s seconds ---" % (time.time() - start_time))
    print('Epoch {0:2d} lr = {1:8.6f} avg loss = {2:8.6f} accuracy = {3:5.2f}'.format(epoch+1, lr_schedule(epoch), (training_loss/num_batches)/DATA_BATCH_SIZE, (100.0*test_correct/test_total)))
    





# model saving
# to use this for checkpointing put this code block inside the training loop at the end (e.g., just indent it 4 spaces)
# and set 'epoch' to the current epoch instead of TRAINING_NUM_EPOCHS - 1; then if there's a crash it will be possible
# to load this checkpoint and restart training from the last complete epoch instead of having to start training at the
# beginning
if FILE_SAVE == 1:
    torch.save({
        'epoch': TRAINING_NUM_EPOCHS - 1,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict()
    }, FILE_NAME)

"""First execution without below part"""